- hosts: finaxLab
  become: yes
  become_user: root
  tasks:


    - name: Install add-apt-repostory
      become: yes
      apt: name=software-properties-common state=latest

    - name: Add Oracle Java Repository
      become: yes
      apt_repository: repo='ppa:webupd8team/java'

    - name: Accept Java 8 License
      become: yes
      debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'

    - name: Install Oracle Java 8
      become: yes
      apt: name={{item}} state=latest
      with_items:
       - oracle-java8-installer
       - ca-certificates
       - oracle-java8-set-default

    # Check if tomcat8 is already installed
    - name: Detect existing tomcat8 installation at /etc/tomcat8$
      stat: path=/etc/tomcat8$
      register: state_of_tomcat8_installation

    - name: Install tomcat8
      apt: name=tomcat8 update_cache=yes state=latest

    - name: Start tomcat
      service: name=tomcat8 state=started

    - name: install maven (and other packages if needed)
      become: yes
      apt: pkg={{ item }} state=latest update_cache=yes cache_valid_time=3600
      with_items:
       - maven

    - name: Install PostgreSQL
      apt: name={{ item }} update_cache=true state=present
      with_items:
      - postgresql
      - postgresql-contrib
      - libpq-dev
      - python-psycopg2
      tags: packages

    - name: Create the postgres user
      postgresql_user:
        name: "{{ db_user }}"
        password: "{{ db_password }}"
        encrypted: True
      become_user: postgres

    - name: create the finaxslackbot db
      postgresql_db:
        name: "{{ db_name }}"
        owner: "{{ db_user }}"
        template: template0
        encoding: UTF8
        lc_collate: 'en_US.UTF-8'
        lc_ctype: 'en_US.UTF-8'
      become_user: postgres

    # Keep at the bottom of the file
    #- name: Source
    #  become_user: root
    #  shell: source .bashrc
